export const signupController = (req: Request, res: Response) => {
  try {
  } catch (error: any) {
    console.log("Error in signupController", error);
  }
};

export const loginController = (req: Request, res: Response) => {
  try {
  } catch (error: any) {
    console.log("Error in loginController", error);
  }
};

export const logoutController = (req: Request, res: Response) => {
  try {
  } catch (error: any) {
    console.log("Error in logoutController", error);
  }
};
